Moved image convert data source files to a single directory
brown-ccv/tiff-volume-2png pull request #21
Opened 2022-09-19 15:17 UTC by kmilo9999

I renamed the main folder to data_converter, and moved the raw-to-tiff and tiff-2-png files to the mentioned folder.
I believe the osom-data-converter should stay on a separate folder, due its resulting raw files can be loaded in the desktop volume viewer without any additional conversions.

2022-09-22 19:29 UTC, mirestrepo requested changes
There still seems to be a `raw_2_tiff` folder. Also, Move the `bosom_converter` also inside. If you are making a package, the submodules at the root level is not standard. 

Running the executables is not the issue. But if someone is every using this package from python directly, you would just want them to be able to say

`from volume_data_converter import osom_to_raw`. Your current set up doesn't allow that

I think `data_converter` is too general... maybe add a 3d or volume in there... we will need to rename the repo  later to match the package

2022-09-22 19:32 UTC, mirestrepo commented
Also - in the `pyproject.toml` you'll want to match the package name so change the line
```
[tool.poetry]
name = "volume-data-converter"
```

other name ideas

`volume-conversion-utils`
`volume-convert`

2022-09-28 20:56 UTC, kmilo9999 commented
- Renamed `data_converter` to `volume_data_converter`
- Moved osom files to `volume_data_converter`
- Modified toml files reflecting changes in the folder structure
- Removed raw_2_tiff folder

2022-09-29 21:00 UTC, mirestrepo approved these changes
Looks great! You left few TODOs that I imagine are coming later...

2022-09-29 21:00 UTC, mirestrepo commented on volume_data_converter/conver_to_8_bit.py
> +                print("TODO")
Don't forget this TODO :)

2022-09-29 21:04 UTC, merged